ServerEvents.recipes(event => {

    event.recipes.gtceu.glass_box('kubejs:glassbox/liquid_glass')
        .itemInputs('#forge:sand')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .outputFluids(Fluid.of('gtceu:glass', 576))
        .duration(10)
        .EUt(240)
        .circuit(2)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass')
        .itemInputs('#forge:sand')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x minecraft:glass')
        .duration(10)
        .EUt(240)
        .circuit(1)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_pane')
        .itemInputs('#forge:sand')
        .notConsumable('gtceu:plate_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x minecraft:glass_pane')
        .duration(10)
        .EUt(240)
        .circuit(1)

    event.recipes.gtceu.glass_box('kubejs:glassbox/tempered_glass')
        .itemInputs('#forge:sand')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:tempered_glass')
        .duration(20)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/laminated_glass')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:plates/polyvinyl_butyral')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('2x gtceu:laminated_glass')
        .duration(40)
        .EUt(240)
        .circuit(4)

    event.recipes.gtceu.glass_box('kubejs:glassbox/quartz_glass')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dusts/certus_quartz')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x ae2:quartz_glass')
        .duration(20)
        .EUt(240)
        .circuit(5)

    event.recipes.gtceu.glass_box('kubejs:glassbox/quartz_vibrant_glass')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dusts/certus_quartz')
        .itemInputs('#forge:dusts/glowstone')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x ae2:quartz_vibrant_glass')
        .duration(20)
        .EUt(240)
        .circuit(6)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_ethereal')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:gems/ender_eye')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_ethereal')
        .duration(20)
        .EUt(240)
        .circuit(7)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_ethereal_reverse')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:gems/ender_eye')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_ethereal_reverse')
        .duration(20)
        .EUt(240)
        .circuit(8)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_ghostly')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:ender_pearls')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_ghostly')
        .duration(20)
        .EUt(240)
        .circuit(9)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_dark_ethereal')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:gems/ender_eye')
        .itemInputs('#forge:dusts/amethyst')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_dark_ethereal')
        .duration(20)
        .EUt(240)
        .circuit(10)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_dark_ethereal_reverse')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:gems/ender_eye')
        .itemInputs('#forge:dusts/amethyst')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_dark_ethereal_reverse')
        .duration(20)
        .EUt(240)
        .circuit(11)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_light')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dusts/glowstone')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_light')
        .duration(20)
        .EUt(240)
        .circuit(12)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_redstone')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dusts/redstone')
        .notConsumable('gtceu:block_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x glassential:glass_redstone')
        .duration(20)
        .EUt(240)
        .circuit(13)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_tube')
        .itemInputs('#forge:sand')
        .notConsumable('gtceu:ball_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:glass_tube')
        .duration(40)
        .EUt(240)
        .circuit(1)

    event.recipes.gtceu.glass_box('kubejs:glassbox/glass_lens')
        .itemInputs('#forge:sand')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(1)

    event.recipes.gtceu.glass_box('kubejs:glassbox/orange_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/orange')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:orange_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/magenta_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/magenta')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:magenta_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/light_blue_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/light_blue')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:light_blue_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/yellow_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/yellow')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:yellow_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/lime_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/lime')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:lime_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/pink_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/pink')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:pink_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/gray_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/gray')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:gray_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/light_gray_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/light_gray')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:light_gray_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/cyan_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/cyan')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:cyan_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/purple_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/purple')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:purple_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/blue_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/blue')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:blue_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/brown_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/brown')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:brown_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/green_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/green')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:green_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/red_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/red')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:red_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

    event.recipes.gtceu.glass_box('kubejs:glassbox/black_glass_lens')
        .itemInputs('#forge:sand')
        .itemInputs('#forge:dyes/black')
        .notConsumable('gtceu:cylinder_casting_mold')
        .inputFluids(Fluid.of('gtceu:oxygen', 500))
        .itemOutputs('4x gtceu:black_glass_lens')
        .duration(10)
        .EUt(240)
        .circuit(3)

})//End Of File