ServerEvents.recipes((event) => {
	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/liquid_glass')
		.itemInputs('#forge:sand')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.outputFluids(Fluid.of('gtceu:glass', 576))
		.duration(10)
		.EUt(240)
		.circuit(2)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/glass')
		.itemInputs('#forge:sand')
		.notConsumable('gtceu:block_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x minecraft:glass')
		.duration(10)
		.EUt(240)
		.circuit(1)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/glass_pane')
		.itemInputs('#forge:sand')
		.notConsumable('gtceu:plate_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x minecraft:glass_pane')
		.duration(10)
		.EUt(240)
		.circuit(1)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/tempered_glass')
		.itemInputs('#forge:sand')
		.notConsumable('gtceu:block_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:tempered_glass')
		.duration(20)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/laminated_glass')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:plates/polyvinyl_butyral')
		.notConsumable('gtceu:block_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('2x gtceu:laminated_glass')
		.duration(40)
		.EUt(240)
		.circuit(4)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/quartz_glass')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dusts/certus_quartz')
		.notConsumable('gtceu:block_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x ae2:quartz_glass')
		.duration(20)
		.EUt(240)
		.circuit(5)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/quartz_vibrant_glass')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dusts/certus_quartz')
		.itemInputs('#forge:dusts/glowstone')
		.notConsumable('gtceu:block_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x ae2:quartz_vibrant_glass')
		.duration(20)
		.EUt(240)
		.circuit(6)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/glass_tube')
		.itemInputs('#forge:sand')
		.notConsumable('gtceu:ball_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:glass_tube')
		.duration(40)
		.EUt(240)
		.circuit(1)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/glass_lens')
		.itemInputs('#forge:sand')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(1)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/orange_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/orange')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:orange_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/magenta_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/magenta')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:magenta_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/light_blue_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/light_blue')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:light_blue_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/yellow_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/yellow')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:yellow_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/lime_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/lime')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:lime_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/pink_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/pink')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:pink_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/gray_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/gray')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:gray_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/light_gray_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/light_gray')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:light_gray_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/cyan_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/cyan')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:cyan_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/purple_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/purple')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:purple_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/blue_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/blue')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:blue_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/brown_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/brown')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:brown_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/green_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/green')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:green_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/red_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/red')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:red_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)

	event.recipes.gtceu
		.glass_forge('kubejs:glassforge/black_glass_lens')
		.itemInputs('#forge:sand')
		.itemInputs('#forge:dyes/black')
		.notConsumable('gtceu:cylinder_casting_mold')
		.inputFluids(Fluid.of('gtceu:oxygen', 500))
		.itemOutputs('4x gtceu:black_glass_lens')
		.duration(10)
		.EUt(240)
		.circuit(3)
}) //End Of File
