ServerEvents.recipes(e => {

    //CB Stuffs
    e.remove({ id: 'chiselandbits:chisel_stone'})
    e.remove({ id: 'chiselandbits:chisel_iron'})
    e.remove({ id: 'chiselandbits:chisel_gold'})
    e.remove({ id: 'chiselandbits:chisel_diamond'})
    e.remove({ id: 'chiselandbits:chisel_netherite'})



    //ReBrassing
    e.remove({ id: 'gtceu:shapeless/dust_brass' })
    e.remove({ id: 'create:mixing/brass_ingot' })

    //RFD Stuffs
    e.remove({ output: 'rfd:clay_gen_tier_1' })
    e.remove({ output: 'rfd:clay_gen_tier_2' })
    e.remove({ output: 'rfd:clay_gen_tier_3' })
    e.remove({ output: 'rfd:clay_gen_tier_4' })
    e.remove({ output: 'rfd:clay_gen_tier_5' })
    e.remove({ output: 'rfd:clean_gen_tier_1' })
    e.remove({ output: 'rfd:clean_gen_tier_2' })
    e.remove({ output: 'rfd:clean_gen_tier_3' })
    e.remove({ output: 'rfd:clean_gen_tier_4' })
    e.remove({ output: 'rfd:clean_gen_tier_5' })
    e.remove({ output: 'rfd:fungus_gen_tier_1' })
    e.remove({ output: 'rfd:fungus_gen_tier_2' })
    e.remove({ output: 'rfd:fungus_gen_tier_3' })
    e.remove({ output: 'rfd:fungus_gen_tier_4' })
    e.remove({ output: 'rfd:fungus_gen_tier_5' })
    e.remove({ output: 'rfd:glowstone_gen_tier_1' })
    e.remove({ output: 'rfd:glowstone_gen_tier_2' })
    e.remove({ output: 'rfd:glowstone_gen_tier_3' })
    e.remove({ output: 'rfd:glowstone_gen_tier_4' })
    e.remove({ output: 'rfd:glowstone_gen_tier_5' })
    e.remove({ output: 'rfd:grass_gen_tier_1' })
    e.remove({ output: 'rfd:grass_gen_tier_2' })
    e.remove({ output: 'rfd:grass_gen_tier_3' })
    e.remove({ output: 'rfd:grass_gen_tier_4' })
    e.remove({ output: 'rfd:grass_gen_tier_5' })
    e.remove({ output: 'rfd:gravel_gen_tier_1' })
    e.remove({ output: 'rfd:gravel_gen_tier_2' })
    e.remove({ output: 'rfd:gravel_gen_tier_3' })
    e.remove({ output: 'rfd:gravel_gen_tier_4' })
    e.remove({ output: 'rfd:gravel_gen_tier_5' })
    e.remove({ output: 'rfd:ice_gen_tier_1' })
    e.remove({ output: 'rfd:ice_gen_tier_2' })
    e.remove({ output: 'rfd:ice_gen_tier_3' })
    e.remove({ output: 'rfd:ice_gen_tier_4' })
    e.remove({ output: 'rfd:ice_gen_tier_5' })
    e.remove({ output: 'rfd:obsidian_gen_tier_1' })
    e.remove({ output: 'rfd:obsidian_gen_tier_2' })
    e.remove({ output: 'rfd:obsidian_gen_tier_3' })
    e.remove({ output: 'rfd:obsidian_gen_tier_4' })
    e.remove({ output: 'rfd:obsidian_gen_tier_5' })
    e.remove({ output: 'rfd:quartz_gen_tier_1' })
    e.remove({ output: 'rfd:quartz_gen_tier_2' })
    e.remove({ output: 'rfd:quartz_gen_tier_3' })
    e.remove({ output: 'rfd:quartz_gen_tier_4' })
    e.remove({ output: 'rfd:quartz_gen_tier_5' })
    e.remove({ output: 'rfd:redstone_gen_tier_1' })
    e.remove({ output: 'rfd:redstone_gen_tier_2' })
    e.remove({ output: 'rfd:redstone_gen_tier_3' })
    e.remove({ output: 'rfd:redstone_gen_tier_4' })
    e.remove({ output: 'rfd:redstone_gen_tier_5' })
    e.remove({ output: 'rfd:snow_gen_tier_1' })
    e.remove({ output: 'rfd:snow_gen_tier_2' })
    e.remove({ output: 'rfd:snow_gen_tier_3' })
    e.remove({ output: 'rfd:snow_gen_tier_4' })
    e.remove({ output: 'rfd:snow_gen_tier_5' })
    e.remove({ output: 'rfd:sand_gen_tier_1' })
    e.remove({ output: 'rfd:sand_gen_tier_2' })
    e.remove({ output: 'rfd:sand_gen_tier_3' })
    e.remove({ output: 'rfd:sand_gen_tier_4' })
    e.remove({ output: 'rfd:sand_gen_tier_5' })
    e.remove({ output: 'rfd:soulsand_gen_tier_1' })
    e.remove({ output: 'rfd:soulsand_gen_tier_2' })
    e.remove({ output: 'rfd:soulsand_gen_tier_3' })
    e.remove({ output: 'rfd:soulsand_gen_tier_4' })
    e.remove({ output: 'rfd:soulsand_gen_tier_5' })
    e.remove({ output: 'rfd:ore_gen_tier_1' })
    e.remove({ output: 'rfd:ore_gen_tier_2' })
    e.remove({ output: 'rfd:ore_gen_tier_3' })
    e.remove({ output: 'rfd:ore_gen_tier_4' })
    e.remove({ output: 'rfd:ore_gen_tier_5' })
    e.remove({ output: 'rfd:dye_gen_tier_1' })
    e.remove({ output: 'rfd:dye_gen_tier_2' })
    e.remove({ output: 'rfd:dye_gen_tier_3' })
    e.remove({ output: 'rfd:dye_gen_tier_4' })
    e.remove({ output: 'rfd:dye_gen_tier_5' })
    e.remove({ output: 'rfd:crushed_netherrack_gen_tier_1' })
    e.remove({ output: 'rfd:crushed_netherrack_gen_tier_2' })
    e.remove({ output: 'rfd:crushed_netherrack_gen_tier_3' })
    e.remove({ output: 'rfd:crushed_netherrack_gen_tier_4' })
    e.remove({ output: 'rfd:crushed_netherrack_gen_tier_5' })
    e.remove({ output: 'rfd:crushed_endstone_gen_tier_1' })
    e.remove({ output: 'rfd:crushed_endstone_gen_tier_2' })
    e.remove({ output: 'rfd:crushed_endstone_gen_tier_3' })
    e.remove({ output: 'rfd:crushed_endstone_gen_tier_4' })
    e.remove({ output: 'rfd:crushed_endstone_gen_tier_5' })
    e.remove({ output: 'rfd:dust_gen_tier_1' })
    e.remove({ output: 'rfd:dust_gen_tier_2' })
    e.remove({ output: 'rfd:dust_gen_tier_3' })
    e.remove({ output: 'rfd:dust_gen_tier_4' })
    e.remove({ output: 'rfd:dust_gen_tier_5' })
    e.remove({ output: 'rfd:ore_gen_tier_1' })
    e.remove({ output: 'rfd:ore_gen_tier_2' })
    e.remove({ output: 'rfd:ore_gen_tier_3' })
    e.remove({ output: 'rfd:ore_gen_tier_4' })
    e.remove({ output: 'rfd:ore_gen_tier_5' })

})//End Of File