// priority: 0

console.info('HIDE ITEMS script loading...')


JEIEvents.hideItems(event => {

event.hide('rfd:clay_gen_tier_1')
event.hide('rfd:clay_gen_tier_2')
event.hide('rfd:clay_gen_tier_3')
event.hide('rfd:clay_gen_tier_4')
event.hide('rfd:clay_gen_tier_5')

event.hide('rfd:clean_gen_tier_1')
event.hide('rfd:clean_gen_tier_2')
event.hide('rfd:clean_gen_tier_3')
event.hide('rfd:clean_gen_tier_4')
event.hide('rfd:clean_gen_tier_5')

event.hide('rfd:fungus_gen_tier_1')
event.hide('rfd:fungus_gen_tier_2')
event.hide('rfd:fungus_gen_tier_3')
event.hide('rfd:fungus_gen_tier_4')
event.hide('rfd:fungus_gen_tier_5')

event.hide('rfd:glowstone_gen_tier_1')
event.hide('rfd:glowstone_gen_tier_2')
event.hide('rfd:glowstone_gen_tier_3')
event.hide('rfd:glowstone_gen_tier_4')
event.hide('rfd:glowstone_gen_tier_5')

event.hide('rfd:grass_gen_tier_1')
event.hide('rfd:grass_gen_tier_2')
event.hide('rfd:grass_gen_tier_3')
event.hide('rfd:grass_gen_tier_4')
event.hide('rfd:grass_gen_tier_5')

event.hide('rfd:gravel_gen_tier_1')
event.hide('rfd:gravel_gen_tier_2')
event.hide('rfd:gravel_gen_tier_3')
event.hide('rfd:gravel_gen_tier_4')
event.hide('rfd:gravel_gen_tier_5')

event.hide('rfd:ice_gen_tier_1')
event.hide('rfd:ice_gen_tier_2')
event.hide('rfd:ice_gen_tier_3')
event.hide('rfd:ice_gen_tier_4')
event.hide('rfd:ice_gen_tier_5')

event.hide('rfd:obsidian_gen_tier_1')
event.hide('rfd:obsidian_gen_tier_2')
event.hide('rfd:obsidian_gen_tier_3')
event.hide('rfd:obsidian_gen_tier_4')
event.hide('rfd:obsidian_gen_tier_5')

event.hide('rfd:quartz_gen_tier_1')
event.hide('rfd:quartz_gen_tier_2')
event.hide('rfd:quartz_gen_tier_3')
event.hide('rfd:quartz_gen_tier_4')
event.hide('rfd:quartz_gen_tier_5')

event.hide('rfd:redstone_gen_tier_1')
event.hide('rfd:redstone_gen_tier_2')
event.hide('rfd:redstone_gen_tier_3')
event.hide('rfd:redstone_gen_tier_4')
event.hide('rfd:redstone_gen_tier_5')

event.hide('rfd:snow_gen_tier_1')
event.hide('rfd:snow_gen_tier_2')
event.hide('rfd:snow_gen_tier_3')
event.hide('rfd:snow_gen_tier_4')
event.hide('rfd:snow_gen_tier_5')

event.hide('rfd:sand_gen_tier_1')
event.hide('rfd:sand_gen_tier_2')
event.hide('rfd:sand_gen_tier_3')
event.hide('rfd:sand_gen_tier_4')
event.hide('rfd:sand_gen_tier_5')

event.hide('rfd:soulsand_gen_tier_1')
event.hide('rfd:soulsand_gen_tier_2')
event.hide('rfd:soulsand_gen_tier_3')
event.hide('rfd:soulsand_gen_tier_4')
event.hide('rfd:soulsand_gen_tier_5')

event.hide('rfd:ore_gen_tier_1')
event.hide('rfd:ore_gen_tier_2')
event.hide('rfd:ore_gen_tier_3')
event.hide('rfd:ore_gen_tier_4')
event.hide('rfd:ore_gen_tier_5')

event.hide('rfd:dye_gen_tier_1')
event.hide('rfd:dye_gen_tier_2')
event.hide('rfd:dye_gen_tier_3')
event.hide('rfd:dye_gen_tier_4')
event.hide('rfd:dye_gen_tier_5')

event.hide('rfd:crushed_netherrack_gen_tier_1')
event.hide('rfd:crushed_netherrack_gen_tier_2')
event.hide('rfd:crushed_netherrack_gen_tier_3')
event.hide('rfd:crushed_netherrack_gen_tier_4')
event.hide('rfd:crushed_netherrack_gen_tier_5')

event.hide('rfd:crushed_endstone_gen_tier_1')
event.hide('rfd:crushed_endstone_gen_tier_2')
event.hide('rfd:crushed_endstone_gen_tier_3')
event.hide('rfd:crushed_endstone_gen_tier_4')
event.hide('rfd:crushed_endstone_gen_tier_5')

event.hide('rfd:dust_gen_tier_1')
event.hide('rfd:dust_gen_tier_2')
event.hide('rfd:dust_gen_tier_3')
event.hide('rfd:dust_gen_tier_4')
event.hide('rfd:dust_gen_tier_5')

event.hide('enderio:broken_spawner')

event.hide('enderio:fused_quartz')
event.hide('enderio:fused_quartz_white')
event.hide('enderio:fused_quartz_orange')
event.hide('enderio:fused_quartz_magenta')
event.hide('enderio:fused_quartz_light_blue')
event.hide('enderio:fused_quartz_yellow')
event.hide('enderio:fused_quartz_lime')
event.hide('enderio:fused_quartz_pink')
event.hide('enderio:fused_quartz_gray')
event.hide('enderio:fused_quartz_light_gray')
event.hide('enderio:fused_quartz_cyan')
event.hide('enderio:fused_quartz_purple')
event.hide('enderio:fused_quartz_blue')
event.hide('enderio:fused_quartz_brown')
event.hide('enderio:fused_quartz_green')
event.hide('enderio:fused_quartz_red')
event.hide('enderio:fused_quartz_black')

event.hide('enderio:fused_quartz_p')
event.hide('enderio:fused_quartz_p_white')
event.hide('enderio:fused_quartz_p_orange')
event.hide('enderio:fused_quartz_p_magenta')
event.hide('enderio:fused_quartz_p_light_blue')
event.hide('enderio:fused_quartz_p_yellow')
event.hide('enderio:fused_quartz_p_lime')
event.hide('enderio:fused_quartz_p_pink')
event.hide('enderio:fused_quartz_p_gray')
event.hide('enderio:fused_quartz_p_light_gray')
event.hide('enderio:fused_quartz_p_cyan')
event.hide('enderio:fused_quartz_p_purple')
event.hide('enderio:fused_quartz_p_blue')
event.hide('enderio:fused_quartz_p_brown')
event.hide('enderio:fused_quartz_p_green')
event.hide('enderio:fused_quartz_p_red')
event.hide('enderio:fused_quartz_p_black')

event.hide('enderio:fused_quartz_np')
event.hide('enderio:fused_quartz_np_white')
event.hide('enderio:fused_quartz_np_orange')
event.hide('enderio:fused_quartz_np_magenta')
event.hide('enderio:fused_quartz_np_light_blue')
event.hide('enderio:fused_quartz_np_yellow')
event.hide('enderio:fused_quartz_np_lime')
event.hide('enderio:fused_quartz_np_pink')
event.hide('enderio:fused_quartz_np_gray')
event.hide('enderio:fused_quartz_np_light_gray')
event.hide('enderio:fused_quartz_np_cyan')
event.hide('enderio:fused_quartz_np_purple')
event.hide('enderio:fused_quartz_np_blue')
event.hide('enderio:fused_quartz_np_brown')
event.hide('enderio:fused_quartz_np_green')
event.hide('enderio:fused_quartz_np_red')
event.hide('enderio:fused_quartz_np_black')

event.hide('enderio:fused_quartz_m')
event.hide('enderio:fused_quartz_m_white')
event.hide('enderio:fused_quartz_m_orange')
event.hide('enderio:fused_quartz_m_magenta')
event.hide('enderio:fused_quartz_m_light_blue')
event.hide('enderio:fused_quartz_m_yellow')
event.hide('enderio:fused_quartz_m_lime')
event.hide('enderio:fused_quartz_m_pink')
event.hide('enderio:fused_quartz_m_gray')
event.hide('enderio:fused_quartz_m_light_gray')
event.hide('enderio:fused_quartz_m_cyan')
event.hide('enderio:fused_quartz_m_purple')
event.hide('enderio:fused_quartz_m_blue')
event.hide('enderio:fused_quartz_m_brown')
event.hide('enderio:fused_quartz_m_green')
event.hide('enderio:fused_quartz_m_red')
event.hide('enderio:fused_quartz_m_black')

event.hide('enderio:fused_quartz_nm')
event.hide('enderio:fused_quartz_nm_white')
event.hide('enderio:fused_quartz_nm_orange')
event.hide('enderio:fused_quartz_nm_magenta')
event.hide('enderio:fused_quartz_nm_light_blue')
event.hide('enderio:fused_quartz_nm_yellow')
event.hide('enderio:fused_quartz_nm_lime')
event.hide('enderio:fused_quartz_nm_pink')
event.hide('enderio:fused_quartz_nm_gray')
event.hide('enderio:fused_quartz_nm_light_gray')
event.hide('enderio:fused_quartz_nm_cyan')
event.hide('enderio:fused_quartz_nm_purple')
event.hide('enderio:fused_quartz_nm_blue')
event.hide('enderio:fused_quartz_nm_brown')
event.hide('enderio:fused_quartz_nm_green')
event.hide('enderio:fused_quartz_nm_red')
event.hide('enderio:fused_quartz_nm_black')

event.hide('enderio:fused_quartz_a')
event.hide('enderio:fused_quartz_a_white')
event.hide('enderio:fused_quartz_a_orange')
event.hide('enderio:fused_quartz_a_magenta')
event.hide('enderio:fused_quartz_a_light_blue')
event.hide('enderio:fused_quartz_a_yellow')
event.hide('enderio:fused_quartz_a_lime')
event.hide('enderio:fused_quartz_a_pink')
event.hide('enderio:fused_quartz_a_gray')
event.hide('enderio:fused_quartz_a_light_gray')
event.hide('enderio:fused_quartz_a_cyan')
event.hide('enderio:fused_quartz_a_purple')
event.hide('enderio:fused_quartz_a_blue')
event.hide('enderio:fused_quartz_a_brown')
event.hide('enderio:fused_quartz_a_green')
event.hide('enderio:fused_quartz_a_red')
event.hide('enderio:fused_quartz_a_black')

event.hide('enderio:fused_quartz_na')
event.hide('enderio:fused_quartz_na_white')
event.hide('enderio:fused_quartz_na_orange')
event.hide('enderio:fused_quartz_na_magenta')
event.hide('enderio:fused_quartz_na_light_blue')
event.hide('enderio:fused_quartz_na_yellow')
event.hide('enderio:fused_quartz_na_lime')
event.hide('enderio:fused_quartz_na_pink')
event.hide('enderio:fused_quartz_na_gray')
event.hide('enderio:fused_quartz_na_light_gray')
event.hide('enderio:fused_quartz_na_cyan')
event.hide('enderio:fused_quartz_na_purple')
event.hide('enderio:fused_quartz_na_blue')
event.hide('enderio:fused_quartz_na_brown')
event.hide('enderio:fused_quartz_na_green')
event.hide('enderio:fused_quartz_na_red')
event.hide('enderio:fused_quartz_na_black')

event.hide('enderio:fused_quartz_d')
event.hide('enderio:fused_quartz_d_white')
event.hide('enderio:fused_quartz_d_orange')
event.hide('enderio:fused_quartz_d_magenta')
event.hide('enderio:fused_quartz_d_light_blue')
event.hide('enderio:fused_quartz_d_yellow')
event.hide('enderio:fused_quartz_d_lime')
event.hide('enderio:fused_quartz_d_pink')
event.hide('enderio:fused_quartz_d_gray')
event.hide('enderio:fused_quartz_d_light_gray')
event.hide('enderio:fused_quartz_d_cyan')
event.hide('enderio:fused_quartz_d_purple')
event.hide('enderio:fused_quartz_d_blue')
event.hide('enderio:fused_quartz_d_brown')
event.hide('enderio:fused_quartz_d_green')
event.hide('enderio:fused_quartz_d_red')
event.hide('enderio:fused_quartz_d_black')

event.hide('enderio:fused_quartz_dp')
event.hide('enderio:fused_quartz_dp_white')
event.hide('enderio:fused_quartz_dp_orange')
event.hide('enderio:fused_quartz_dp_magenta')
event.hide('enderio:fused_quartz_dp_light_blue')
event.hide('enderio:fused_quartz_dp_yellow')
event.hide('enderio:fused_quartz_dp_lime')
event.hide('enderio:fused_quartz_dp_pink')
event.hide('enderio:fused_quartz_dp_gray')
event.hide('enderio:fused_quartz_dp_light_gray')
event.hide('enderio:fused_quartz_dp_cyan')
event.hide('enderio:fused_quartz_dp_purple')
event.hide('enderio:fused_quartz_dp_blue')
event.hide('enderio:fused_quartz_dp_brown')
event.hide('enderio:fused_quartz_dp_green')
event.hide('enderio:fused_quartz_dp_red')
event.hide('enderio:fused_quartz_dp_black')

event.hide('enderio:fused_quartz_dnp')
event.hide('enderio:fused_quartz_dnp_white')
event.hide('enderio:fused_quartz_dnp_orange')
event.hide('enderio:fused_quartz_dnp_magenta')
event.hide('enderio:fused_quartz_dnp_light_blue')
event.hide('enderio:fused_quartz_dnp_yellow')
event.hide('enderio:fused_quartz_dnp_lime')
event.hide('enderio:fused_quartz_dnp_pink')
event.hide('enderio:fused_quartz_dnp_gray')
event.hide('enderio:fused_quartz_dnp_light_gray')
event.hide('enderio:fused_quartz_dnp_cyan')
event.hide('enderio:fused_quartz_dnp_purple')
event.hide('enderio:fused_quartz_dnp_blue')
event.hide('enderio:fused_quartz_dnp_brown')
event.hide('enderio:fused_quartz_dnp_green')
event.hide('enderio:fused_quartz_dnp_red')
event.hide('enderio:fused_quartz_dnp_black')

event.hide('enderio:fused_quartz_dm')
event.hide('enderio:fused_quartz_dm_white')
event.hide('enderio:fused_quartz_dm_orange')
event.hide('enderio:fused_quartz_dm_magenta')
event.hide('enderio:fused_quartz_dm_light_blue')
event.hide('enderio:fused_quartz_dm_yellow')
event.hide('enderio:fused_quartz_dm_lime')
event.hide('enderio:fused_quartz_dm_pink')
event.hide('enderio:fused_quartz_dm_gray')
event.hide('enderio:fused_quartz_dm_light_gray')
event.hide('enderio:fused_quartz_dm_cyan')
event.hide('enderio:fused_quartz_dm_purple')
event.hide('enderio:fused_quartz_dm_blue')
event.hide('enderio:fused_quartz_dm_brown')
event.hide('enderio:fused_quartz_dm_green')
event.hide('enderio:fused_quartz_dm_red')
event.hide('enderio:fused_quartz_dm_black')

event.hide('enderio:fused_quartz_dnm')
event.hide('enderio:fused_quartz_dnm_white')
event.hide('enderio:fused_quartz_dnm_orange')
event.hide('enderio:fused_quartz_dnm_magenta')
event.hide('enderio:fused_quartz_dnm_light_blue')
event.hide('enderio:fused_quartz_dnm_yellow')
event.hide('enderio:fused_quartz_dnm_lime')
event.hide('enderio:fused_quartz_dnm_pink')
event.hide('enderio:fused_quartz_dnm_gray')
event.hide('enderio:fused_quartz_dnm_light_gray')
event.hide('enderio:fused_quartz_dnm_cyan')
event.hide('enderio:fused_quartz_dnm_purple')
event.hide('enderio:fused_quartz_dnm_blue')
event.hide('enderio:fused_quartz_dnm_brown')
event.hide('enderio:fused_quartz_dnm_green')
event.hide('enderio:fused_quartz_dnm_red')
event.hide('enderio:fused_quartz_dnm_black')

event.hide('enderio:fused_quartz_da')
event.hide('enderio:fused_quartz_da_white')
event.hide('enderio:fused_quartz_da_orange')
event.hide('enderio:fused_quartz_da_magenta')
event.hide('enderio:fused_quartz_da_light_blue')
event.hide('enderio:fused_quartz_da_yellow')
event.hide('enderio:fused_quartz_da_lime')
event.hide('enderio:fused_quartz_da_pink')
event.hide('enderio:fused_quartz_da_gray')
event.hide('enderio:fused_quartz_da_light_gray')
event.hide('enderio:fused_quartz_da_cyan')
event.hide('enderio:fused_quartz_da_purple')
event.hide('enderio:fused_quartz_da_blue')
event.hide('enderio:fused_quartz_da_brown')
event.hide('enderio:fused_quartz_da_green')
event.hide('enderio:fused_quartz_da_red')
event.hide('enderio:fused_quartz_da_black')

event.hide('enderio:fused_quartz_dna')
event.hide('enderio:fused_quartz_dna_white')
event.hide('enderio:fused_quartz_dna_orange')
event.hide('enderio:fused_quartz_dna_magenta')
event.hide('enderio:fused_quartz_dna_light_blue')
event.hide('enderio:fused_quartz_dna_yellow')
event.hide('enderio:fused_quartz_dna_lime')
event.hide('enderio:fused_quartz_dna_pink')
event.hide('enderio:fused_quartz_dna_gray')
event.hide('enderio:fused_quartz_dna_light_gray')
event.hide('enderio:fused_quartz_dna_cyan')
event.hide('enderio:fused_quartz_dna_purple')
event.hide('enderio:fused_quartz_dna_blue')
event.hide('enderio:fused_quartz_dna_brown')
event.hide('enderio:fused_quartz_dna_green')
event.hide('enderio:fused_quartz_dna_red')
event.hide('enderio:fused_quartz_dna_black')

event.hide('enderio:fused_quartz_e')
event.hide('enderio:fused_quartz_e_white')
event.hide('enderio:fused_quartz_e_orange')
event.hide('enderio:fused_quartz_e_magenta')
event.hide('enderio:fused_quartz_e_light_blue')
event.hide('enderio:fused_quartz_e_yellow')
event.hide('enderio:fused_quartz_e_lime')
event.hide('enderio:fused_quartz_e_pink')
event.hide('enderio:fused_quartz_e_gray')
event.hide('enderio:fused_quartz_e_light_gray')
event.hide('enderio:fused_quartz_e_cyan')
event.hide('enderio:fused_quartz_e_purple')
event.hide('enderio:fused_quartz_e_blue')
event.hide('enderio:fused_quartz_e_brown')
event.hide('enderio:fused_quartz_e_green')
event.hide('enderio:fused_quartz_e_red')
event.hide('enderio:fused_quartz_e_black')

event.hide('enderio:fused_quartz_ep')
event.hide('enderio:fused_quartz_ep_white')
event.hide('enderio:fused_quartz_ep_orange')
event.hide('enderio:fused_quartz_ep_magenta')
event.hide('enderio:fused_quartz_ep_light_blue')
event.hide('enderio:fused_quartz_ep_yellow')
event.hide('enderio:fused_quartz_ep_lime')
event.hide('enderio:fused_quartz_ep_pink')
event.hide('enderio:fused_quartz_ep_gray')
event.hide('enderio:fused_quartz_ep_light_gray')
event.hide('enderio:fused_quartz_ep_cyan')
event.hide('enderio:fused_quartz_ep_purple')
event.hide('enderio:fused_quartz_ep_blue')
event.hide('enderio:fused_quartz_ep_brown')
event.hide('enderio:fused_quartz_ep_green')
event.hide('enderio:fused_quartz_ep_red')
event.hide('enderio:fused_quartz_ep_black')

event.hide('enderio:fused_quartz_enp')
event.hide('enderio:fused_quartz_enp_white')
event.hide('enderio:fused_quartz_enp_orange')
event.hide('enderio:fused_quartz_enp_magenta')
event.hide('enderio:fused_quartz_enp_light_blue')
event.hide('enderio:fused_quartz_enp_yellow')
event.hide('enderio:fused_quartz_enp_lime')
event.hide('enderio:fused_quartz_enp_pink')
event.hide('enderio:fused_quartz_enp_gray')
event.hide('enderio:fused_quartz_enp_light_gray')
event.hide('enderio:fused_quartz_enp_cyan')
event.hide('enderio:fused_quartz_enp_purple')
event.hide('enderio:fused_quartz_enp_blue')
event.hide('enderio:fused_quartz_enp_brown')
event.hide('enderio:fused_quartz_enp_green')
event.hide('enderio:fused_quartz_enp_red')
event.hide('enderio:fused_quartz_enp_black')

event.hide('enderio:fused_quartz_em')
event.hide('enderio:fused_quartz_em_white')
event.hide('enderio:fused_quartz_em_orange')
event.hide('enderio:fused_quartz_em_magenta')
event.hide('enderio:fused_quartz_em_light_blue')
event.hide('enderio:fused_quartz_em_yellow')
event.hide('enderio:fused_quartz_em_lime')
event.hide('enderio:fused_quartz_em_pink')
event.hide('enderio:fused_quartz_em_gray')
event.hide('enderio:fused_quartz_em_light_gray')
event.hide('enderio:fused_quartz_em_cyan')
event.hide('enderio:fused_quartz_em_purple')
event.hide('enderio:fused_quartz_em_blue')
event.hide('enderio:fused_quartz_em_brown')
event.hide('enderio:fused_quartz_em_green')
event.hide('enderio:fused_quartz_em_red')
event.hide('enderio:fused_quartz_em_black')

event.hide('enderio:fused_quartz_emn')
event.hide('enderio:fused_quartz_emn_white')
event.hide('enderio:fused_quartz_emn_orange')
event.hide('enderio:fused_quartz_emn_magenta')
event.hide('enderio:fused_quartz_emn_light_blue')
event.hide('enderio:fused_quartz_emn_yellow')
event.hide('enderio:fused_quartz_emn_lime')
event.hide('enderio:fused_quartz_emn_pink')
event.hide('enderio:fused_quartz_emn_gray')
event.hide('enderio:fused_quartz_emn_light_gray')
event.hide('enderio:fused_quartz_emn_cyan')
event.hide('enderio:fused_quartz_emn_purple')
event.hide('enderio:fused_quartz_emn_blue')
event.hide('enderio:fused_quartz_emn_brown')
event.hide('enderio:fused_quartz_emn_green')
event.hide('enderio:fused_quartz_emn_red')
event.hide('enderio:fused_quartz_emn_black')

event.hide('enderio:fused_quartz_ea')
event.hide('enderio:fused_quartz_ea_white')
event.hide('enderio:fused_quartz_ea_orange')
event.hide('enderio:fused_quartz_ea_magenta')
event.hide('enderio:fused_quartz_ea_light_blue')
event.hide('enderio:fused_quartz_ea_yellow')
event.hide('enderio:fused_quartz_ea_lime')
event.hide('enderio:fused_quartz_ea_pink')
event.hide('enderio:fused_quartz_ea_gray')
event.hide('enderio:fused_quartz_ea_light_gray')
event.hide('enderio:fused_quartz_ea_cyan')
event.hide('enderio:fused_quartz_ea_purple')
event.hide('enderio:fused_quartz_ea_blue')
event.hide('enderio:fused_quartz_ea_brown')
event.hide('enderio:fused_quartz_ea_green')
event.hide('enderio:fused_quartz_ea_red')
event.hide('enderio:fused_quartz_ea_black')

event.hide('enderio:fused_quartz_ena')
event.hide('enderio:fused_quartz_ena_white')
event.hide('enderio:fused_quartz_ena_orange')
event.hide('enderio:fused_quartz_ena_magenta')
event.hide('enderio:fused_quartz_ena_light_blue')
event.hide('enderio:fused_quartz_ena_yellow')
event.hide('enderio:fused_quartz_ena_lime')
event.hide('enderio:fused_quartz_ena_pink')
event.hide('enderio:fused_quartz_ena_gray')
event.hide('enderio:fused_quartz_ena_light_gray')
event.hide('enderio:fused_quartz_ena_cyan')
event.hide('enderio:fused_quartz_ena_purple')
event.hide('enderio:fused_quartz_ena_blue')
event.hide('enderio:fused_quartz_ena_brown')
event.hide('enderio:fused_quartz_ena_green')
event.hide('enderio:fused_quartz_ena_red')
event.hide('enderio:fused_quartz_ena_black')

event.hide('enderio:fused_quartz_enm')
event.hide('enderio:fused_quartz_enm_white')
event.hide('enderio:fused_quartz_enm_orange')
event.hide('enderio:fused_quartz_enm_magenta')
event.hide('enderio:fused_quartz_enm_light_blue')
event.hide('enderio:fused_quartz_enm_yellow')
event.hide('enderio:fused_quartz_enm_lime')
event.hide('enderio:fused_quartz_enm_pink')
event.hide('enderio:fused_quartz_enm_gray')
event.hide('enderio:fused_quartz_enm_light_gray')
event.hide('enderio:fused_quartz_enm_cyan')
event.hide('enderio:fused_quartz_enm_purple')
event.hide('enderio:fused_quartz_enm_blue')
event.hide('enderio:fused_quartz_enm_brown')
event.hide('enderio:fused_quartz_enm_green')
event.hide('enderio:fused_quartz_enm_red')
event.hide('enderio:fused_quartz_enm_black')

event.hide('enderio:clear_glass')
event.hide('enderio:clear_glass_white')
event.hide('enderio:clear_glass_orange')
event.hide('enderio:clear_glass_magenta')
event.hide('enderio:clear_glass_light_blue')
event.hide('enderio:clear_glass_yellow')
event.hide('enderio:clear_glass_lime')
event.hide('enderio:clear_glass_pink')
event.hide('enderio:clear_glass_gray')
event.hide('enderio:clear_glass_light_gray')
event.hide('enderio:clear_glass_cyan')
event.hide('enderio:clear_glass_purple')
event.hide('enderio:clear_glass_blue')
event.hide('enderio:clear_glass_brown')
event.hide('enderio:clear_glass_green')
event.hide('enderio:clear_glass_red')
event.hide('enderio:clear_glass_black')

event.hide('enderio:clear_glass_p')
event.hide('enderio:clear_glass_p_white')
event.hide('enderio:clear_glass_p_orange')
event.hide('enderio:clear_glass_p_magenta')
event.hide('enderio:clear_glass_p_light_blue')
event.hide('enderio:clear_glass_p_yellow')
event.hide('enderio:clear_glass_p_lime')
event.hide('enderio:clear_glass_p_pink')
event.hide('enderio:clear_glass_p_gray')
event.hide('enderio:clear_glass_p_light_gray')
event.hide('enderio:clear_glass_p_cyan')
event.hide('enderio:clear_glass_p_purple')
event.hide('enderio:clear_glass_p_blue')
event.hide('enderio:clear_glass_p_brown')
event.hide('enderio:clear_glass_p_green')
event.hide('enderio:clear_glass_p_red')
event.hide('enderio:clear_glass_p_black')

event.hide('enderio:clear_glass_np')
event.hide('enderio:clear_glass_np_white')
event.hide('enderio:clear_glass_np_orange')
event.hide('enderio:clear_glass_np_magenta')
event.hide('enderio:clear_glass_np_light_blue')
event.hide('enderio:clear_glass_np_yellow')
event.hide('enderio:clear_glass_np_lime')
event.hide('enderio:clear_glass_np_pink')
event.hide('enderio:clear_glass_np_gray')
event.hide('enderio:clear_glass_np_light_gray')
event.hide('enderio:clear_glass_np_cyan')
event.hide('enderio:clear_glass_np_purple')
event.hide('enderio:clear_glass_np_blue')
event.hide('enderio:clear_glass_np_brown')
event.hide('enderio:clear_glass_np_green')
event.hide('enderio:clear_glass_np_red')
event.hide('enderio:clear_glass_np_black')

event.hide('enderio:clear_glass_m')
event.hide('enderio:clear_glass_m_white')
event.hide('enderio:clear_glass_m_orange')
event.hide('enderio:clear_glass_m_magenta')
event.hide('enderio:clear_glass_m_light_blue')
event.hide('enderio:clear_glass_m_yellow')
event.hide('enderio:clear_glass_m_lime')
event.hide('enderio:clear_glass_m_pink')
event.hide('enderio:clear_glass_m_gray')
event.hide('enderio:clear_glass_m_light_gray')
event.hide('enderio:clear_glass_m_cyan')
event.hide('enderio:clear_glass_m_purple')
event.hide('enderio:clear_glass_m_blue')
event.hide('enderio:clear_glass_m_brown')
event.hide('enderio:clear_glass_m_green')
event.hide('enderio:clear_glass_m_red')
event.hide('enderio:clear_glass_m_black')

event.hide('enderio:clear_glass_nm')
event.hide('enderio:clear_glass_nm_white')
event.hide('enderio:clear_glass_nm_orange')
event.hide('enderio:clear_glass_nm_magenta')
event.hide('enderio:clear_glass_nm_light_blue')
event.hide('enderio:clear_glass_nm_yellow')
event.hide('enderio:clear_glass_nm_lime')
event.hide('enderio:clear_glass_nm_pink')
event.hide('enderio:clear_glass_nm_gray')
event.hide('enderio:clear_glass_nm_light_gray')
event.hide('enderio:clear_glass_nm_cyan')
event.hide('enderio:clear_glass_nm_purple')
event.hide('enderio:clear_glass_nm_blue')
event.hide('enderio:clear_glass_nm_brown')
event.hide('enderio:clear_glass_nm_green')
event.hide('enderio:clear_glass_nm_red')
event.hide('enderio:clear_glass_nm_black')

event.hide('enderio:clear_glass_a')
event.hide('enderio:clear_glass_a_white')
event.hide('enderio:clear_glass_a_orange')
event.hide('enderio:clear_glass_a_magenta')
event.hide('enderio:clear_glass_a_light_blue')
event.hide('enderio:clear_glass_a_yellow')
event.hide('enderio:clear_glass_a_lime')
event.hide('enderio:clear_glass_a_pink')
event.hide('enderio:clear_glass_a_gray')
event.hide('enderio:clear_glass_a_light_gray')
event.hide('enderio:clear_glass_a_cyan')
event.hide('enderio:clear_glass_a_purple')
event.hide('enderio:clear_glass_a_blue')
event.hide('enderio:clear_glass_a_brown')
event.hide('enderio:clear_glass_a_green')
event.hide('enderio:clear_glass_a_red')
event.hide('enderio:clear_glass_a_black')

event.hide('enderio:clear_glass_na')
event.hide('enderio:clear_glass_na_white')
event.hide('enderio:clear_glass_na_orange')
event.hide('enderio:clear_glass_na_magenta')
event.hide('enderio:clear_glass_na_light_blue')
event.hide('enderio:clear_glass_na_yellow')
event.hide('enderio:clear_glass_na_lime')
event.hide('enderio:clear_glass_na_pink')
event.hide('enderio:clear_glass_na_gray')
event.hide('enderio:clear_glass_na_light_gray')
event.hide('enderio:clear_glass_na_cyan')
event.hide('enderio:clear_glass_na_purple')
event.hide('enderio:clear_glass_na_blue')
event.hide('enderio:clear_glass_na_brown')
event.hide('enderio:clear_glass_na_green')
event.hide('enderio:clear_glass_na_red')
event.hide('enderio:clear_glass_na_black')

event.hide('enderio:clear_glass_d')
event.hide('enderio:clear_glass_d_white')
event.hide('enderio:clear_glass_d_orange')
event.hide('enderio:clear_glass_d_magenta')
event.hide('enderio:clear_glass_d_light_blue')
event.hide('enderio:clear_glass_d_yellow')
event.hide('enderio:clear_glass_d_lime')
event.hide('enderio:clear_glass_d_pink')
event.hide('enderio:clear_glass_d_gray')
event.hide('enderio:clear_glass_d_light_gray')
event.hide('enderio:clear_glass_d_cyan')
event.hide('enderio:clear_glass_d_purple')
event.hide('enderio:clear_glass_d_blue')
event.hide('enderio:clear_glass_d_brown')
event.hide('enderio:clear_glass_d_green')
event.hide('enderio:clear_glass_d_red')
event.hide('enderio:clear_glass_d_black')

event.hide('enderio:clear_glass_dp')
event.hide('enderio:clear_glass_dp_white')
event.hide('enderio:clear_glass_dp_orange')
event.hide('enderio:clear_glass_dp_magenta')
event.hide('enderio:clear_glass_dp_light_blue')
event.hide('enderio:clear_glass_dp_yellow')
event.hide('enderio:clear_glass_dp_lime')
event.hide('enderio:clear_glass_dp_pink')
event.hide('enderio:clear_glass_dp_gray')
event.hide('enderio:clear_glass_dp_light_gray')
event.hide('enderio:clear_glass_dp_cyan')
event.hide('enderio:clear_glass_dp_purple')
event.hide('enderio:clear_glass_dp_blue')
event.hide('enderio:clear_glass_dp_brown')
event.hide('enderio:clear_glass_dp_green')
event.hide('enderio:clear_glass_dp_red')
event.hide('enderio:clear_glass_dp_black')

event.hide('enderio:clear_glass_dnp')
event.hide('enderio:clear_glass_dnp_white')
event.hide('enderio:clear_glass_dnp_orange')
event.hide('enderio:clear_glass_dnp_magenta')
event.hide('enderio:clear_glass_dnp_light_blue')
event.hide('enderio:clear_glass_dnp_yellow')
event.hide('enderio:clear_glass_dnp_lime')
event.hide('enderio:clear_glass_dnp_pink')
event.hide('enderio:clear_glass_dnp_gray')
event.hide('enderio:clear_glass_dnp_light_gray')
event.hide('enderio:clear_glass_dnp_cyan')
event.hide('enderio:clear_glass_dnp_purple')
event.hide('enderio:clear_glass_dnp_blue')
event.hide('enderio:clear_glass_dnp_brown')
event.hide('enderio:clear_glass_dnp_green')
event.hide('enderio:clear_glass_dnp_red')
event.hide('enderio:clear_glass_dnp_black')

event.hide('enderio:clear_glass_dm')
event.hide('enderio:clear_glass_dm_white')
event.hide('enderio:clear_glass_dm_orange')
event.hide('enderio:clear_glass_dm_magenta')
event.hide('enderio:clear_glass_dm_light_blue')
event.hide('enderio:clear_glass_dm_yellow')
event.hide('enderio:clear_glass_dm_lime')
event.hide('enderio:clear_glass_dm_pink')
event.hide('enderio:clear_glass_dm_gray')
event.hide('enderio:clear_glass_dm_light_gray')
event.hide('enderio:clear_glass_dm_cyan')
event.hide('enderio:clear_glass_dm_purple')
event.hide('enderio:clear_glass_dm_blue')
event.hide('enderio:clear_glass_dm_brown')
event.hide('enderio:clear_glass_dm_green')
event.hide('enderio:clear_glass_dm_red')
event.hide('enderio:clear_glass_dm_black')

event.hide('enderio:clear_glass_dnm')
event.hide('enderio:clear_glass_dnm_white')
event.hide('enderio:clear_glass_dnm_orange')
event.hide('enderio:clear_glass_dnm_magenta')
event.hide('enderio:clear_glass_dnm_light_blue')
event.hide('enderio:clear_glass_dnm_yellow')
event.hide('enderio:clear_glass_dnm_lime')
event.hide('enderio:clear_glass_dnm_pink')
event.hide('enderio:clear_glass_dnm_gray')
event.hide('enderio:clear_glass_dnm_light_gray')
event.hide('enderio:clear_glass_dnm_cyan')
event.hide('enderio:clear_glass_dnm_purple')
event.hide('enderio:clear_glass_dnm_blue')
event.hide('enderio:clear_glass_dnm_brown')
event.hide('enderio:clear_glass_dnm_green')
event.hide('enderio:clear_glass_dnm_red')
event.hide('enderio:clear_glass_dnm_black')

event.hide('enderio:clear_glass_da')
event.hide('enderio:clear_glass_da_white')
event.hide('enderio:clear_glass_da_orange')
event.hide('enderio:clear_glass_da_magenta')
event.hide('enderio:clear_glass_da_light_blue')
event.hide('enderio:clear_glass_da_yellow')
event.hide('enderio:clear_glass_da_lime')
event.hide('enderio:clear_glass_da_pink')
event.hide('enderio:clear_glass_da_gray')
event.hide('enderio:clear_glass_da_light_gray')
event.hide('enderio:clear_glass_da_cyan')
event.hide('enderio:clear_glass_da_purple')
event.hide('enderio:clear_glass_da_blue')
event.hide('enderio:clear_glass_da_brown')
event.hide('enderio:clear_glass_da_green')
event.hide('enderio:clear_glass_da_red')
event.hide('enderio:clear_glass_da_black')

event.hide('enderio:clear_glass_dna')
event.hide('enderio:clear_glass_dna_white')
event.hide('enderio:clear_glass_dna_orange')
event.hide('enderio:clear_glass_dna_magenta')
event.hide('enderio:clear_glass_dna_light_blue')
event.hide('enderio:clear_glass_dna_yellow')
event.hide('enderio:clear_glass_dna_lime')
event.hide('enderio:clear_glass_dna_pink')
event.hide('enderio:clear_glass_dna_gray')
event.hide('enderio:clear_glass_dna_light_gray')
event.hide('enderio:clear_glass_dna_cyan')
event.hide('enderio:clear_glass_dna_purple')
event.hide('enderio:clear_glass_dna_blue')
event.hide('enderio:clear_glass_dna_brown')
event.hide('enderio:clear_glass_dna_green')
event.hide('enderio:clear_glass_dna_red')
event.hide('enderio:clear_glass_dna_black')

event.hide('enderio:clear_glass_e')
event.hide('enderio:clear_glass_e_white')
event.hide('enderio:clear_glass_e_orange')
event.hide('enderio:clear_glass_e_magenta')
event.hide('enderio:clear_glass_e_light_blue')
event.hide('enderio:clear_glass_e_yellow')
event.hide('enderio:clear_glass_e_lime')
event.hide('enderio:clear_glass_e_pink')
event.hide('enderio:clear_glass_e_gray')
event.hide('enderio:clear_glass_e_light_gray')
event.hide('enderio:clear_glass_e_cyan')
event.hide('enderio:clear_glass_e_purple')
event.hide('enderio:clear_glass_e_blue')
event.hide('enderio:clear_glass_e_brown')
event.hide('enderio:clear_glass_e_green')
event.hide('enderio:clear_glass_e_red')
event.hide('enderio:clear_glass_e_black')

event.hide('enderio:clear_glass_ep')
event.hide('enderio:clear_glass_ep_white')
event.hide('enderio:clear_glass_ep_orange')
event.hide('enderio:clear_glass_ep_magenta')
event.hide('enderio:clear_glass_ep_light_blue')
event.hide('enderio:clear_glass_ep_yellow')
event.hide('enderio:clear_glass_ep_lime')
event.hide('enderio:clear_glass_ep_pink')
event.hide('enderio:clear_glass_ep_gray')
event.hide('enderio:clear_glass_ep_light_gray')
event.hide('enderio:clear_glass_ep_cyan')
event.hide('enderio:clear_glass_ep_purple')
event.hide('enderio:clear_glass_ep_blue')
event.hide('enderio:clear_glass_ep_brown')
event.hide('enderio:clear_glass_ep_green')
event.hide('enderio:clear_glass_ep_red')
event.hide('enderio:clear_glass_ep_black')

event.hide('enderio:clear_glass_enp')
event.hide('enderio:clear_glass_enp_white')
event.hide('enderio:clear_glass_enp_orange')
event.hide('enderio:clear_glass_enp_magenta')
event.hide('enderio:clear_glass_enp_light_blue')
event.hide('enderio:clear_glass_enp_yellow')
event.hide('enderio:clear_glass_enp_lime')
event.hide('enderio:clear_glass_enp_pink')
event.hide('enderio:clear_glass_enp_gray')
event.hide('enderio:clear_glass_enp_light_gray')
event.hide('enderio:clear_glass_enp_cyan')
event.hide('enderio:clear_glass_enp_purple')
event.hide('enderio:clear_glass_enp_blue')
event.hide('enderio:clear_glass_enp_brown')
event.hide('enderio:clear_glass_enp_green')
event.hide('enderio:clear_glass_enp_red')
event.hide('enderio:clear_glass_enp_black')

event.hide('enderio:clear_glass_em')
event.hide('enderio:clear_glass_em_white')
event.hide('enderio:clear_glass_em_orange')
event.hide('enderio:clear_glass_em_magenta')
event.hide('enderio:clear_glass_em_light_blue')
event.hide('enderio:clear_glass_em_yellow')
event.hide('enderio:clear_glass_em_lime')
event.hide('enderio:clear_glass_em_pink')
event.hide('enderio:clear_glass_em_gray')
event.hide('enderio:clear_glass_em_light_gray')
event.hide('enderio:clear_glass_em_cyan')
event.hide('enderio:clear_glass_em_purple')
event.hide('enderio:clear_glass_em_blue')
event.hide('enderio:clear_glass_em_brown')
event.hide('enderio:clear_glass_em_green')
event.hide('enderio:clear_glass_em_red')
event.hide('enderio:clear_glass_em_black')

event.hide('enderio:clear_glass_emn')
event.hide('enderio:clear_glass_emn_white')
event.hide('enderio:clear_glass_emn_orange')
event.hide('enderio:clear_glass_emn_magenta')
event.hide('enderio:clear_glass_emn_light_blue')
event.hide('enderio:clear_glass_emn_yellow')
event.hide('enderio:clear_glass_emn_lime')
event.hide('enderio:clear_glass_emn_pink')
event.hide('enderio:clear_glass_emn_gray')
event.hide('enderio:clear_glass_emn_light_gray')
event.hide('enderio:clear_glass_emn_cyan')
event.hide('enderio:clear_glass_emn_purple')
event.hide('enderio:clear_glass_emn_blue')
event.hide('enderio:clear_glass_emn_brown')
event.hide('enderio:clear_glass_emn_green')
event.hide('enderio:clear_glass_emn_red')
event.hide('enderio:clear_glass_emn_black')

event.hide('enderio:clear_glass_ea')
event.hide('enderio:clear_glass_ea_white')
event.hide('enderio:clear_glass_ea_orange')
event.hide('enderio:clear_glass_ea_magenta')
event.hide('enderio:clear_glass_ea_light_blue')
event.hide('enderio:clear_glass_ea_yellow')
event.hide('enderio:clear_glass_ea_lime')
event.hide('enderio:clear_glass_ea_pink')
event.hide('enderio:clear_glass_ea_gray')
event.hide('enderio:clear_glass_ea_light_gray')
event.hide('enderio:clear_glass_ea_cyan')
event.hide('enderio:clear_glass_ea_purple')
event.hide('enderio:clear_glass_ea_blue')
event.hide('enderio:clear_glass_ea_brown')
event.hide('enderio:clear_glass_ea_green')
event.hide('enderio:clear_glass_ea_red')
event.hide('enderio:clear_glass_ea_black')

event.hide('enderio:clear_glass_ena')
event.hide('enderio:clear_glass_ena_white')
event.hide('enderio:clear_glass_ena_orange')
event.hide('enderio:clear_glass_ena_magenta')
event.hide('enderio:clear_glass_ena_light_blue')
event.hide('enderio:clear_glass_ena_yellow')
event.hide('enderio:clear_glass_ena_lime')
event.hide('enderio:clear_glass_ena_pink')
event.hide('enderio:clear_glass_ena_gray')
event.hide('enderio:clear_glass_ena_light_gray')
event.hide('enderio:clear_glass_ena_cyan')
event.hide('enderio:clear_glass_ena_purple')
event.hide('enderio:clear_glass_ena_blue')
event.hide('enderio:clear_glass_ena_brown')
event.hide('enderio:clear_glass_ena_green')
event.hide('enderio:clear_glass_ena_red')
event.hide('enderio:clear_glass_ena_black')

event.hide('enderio:clear_glass_enm')
event.hide('enderio:clear_glass_enm_white')
event.hide('enderio:clear_glass_enm_orange')
event.hide('enderio:clear_glass_enm_magenta')
event.hide('enderio:clear_glass_enm_light_blue')
event.hide('enderio:clear_glass_enm_yellow')
event.hide('enderio:clear_glass_enm_lime')
event.hide('enderio:clear_glass_enm_pink')
event.hide('enderio:clear_glass_enm_gray')
event.hide('enderio:clear_glass_enm_light_gray')
event.hide('enderio:clear_glass_enm_cyan')
event.hide('enderio:clear_glass_enm_purple')
event.hide('enderio:clear_glass_enm_blue')
event.hide('enderio:clear_glass_enm_brown')
event.hide('enderio:clear_glass_enm_green')
event.hide('enderio:clear_glass_enm_red')
event.hide('enderio:clear_glass_enm_black')

event.hide('enderio:painted_fence')
event.hide('enderio:painted_fence_gate')
event.hide('enderio:painted_sand')
event.hide('enderio:painted_stairs')
event.hide('enderio:painted_crafting_table')
event.hide('enderio:painted_redstone_block')
event.hide('enderio:painted_trapdoor')
event.hide('enderio:painted_wooden_pressure_plate')
event.hide('enderio:painted_slab')
event.hide('enderio:painted_glowstone')
event.hide('enderio:painted_glowstone')

event.hide('enderio:light')
event.hide('enderio:light_inverted')
event.hide('enderio:powered_light')
event.hide('enderio:powered_light_inverted')
event.hide('enderio:powered_light_wireless')
event.hide('enderio:powered_light_inverted_wireless')

event.hide('enderio:resetting_lever_five')
event.hide('enderio:resetting_lever_ten')
event.hide('enderio:resetting_lever_thirty')
event.hide('enderio:resetting_lever_sixty')
event.hide('enderio:resetting_lever_three_hundred')
event.hide('enderio:resetting_lever_five_inv')
event.hide('enderio:resetting_lever_ten_inv')
event.hide('enderio:resetting_lever_thirty_inv')
event.hide('enderio:resetting_lever_sixty_inv')
event.hide('enderio:resetting_lever_three_hundred_inv')

event.hide('enderio:wood_gear')
event.hide('enderio:stone_gear')
event.hide('enderio:iron_gear')
event.hide('enderio:dark_bimetal_gear')
event.hide('enderio:energized_gear')
event.hide('enderio:vibrant_gear')

event.hide('enderio:copper_alloy_ingot')
event.hide('enderio:energetic_alloy_ingot')
event.hide('enderio:vibrant_alloy_ingot')
event.hide('enderio:redstone_alloy_ingot')
event.hide('enderio:conductive_alloy_ingot')
event.hide('enderio:pulsating_alloy_ingot')
event.hide('enderio:dark_steel_ingot')
event.hide('enderio:soularium_ingot')
event.hide('enderio:end_steel_ingot')

/* event.hide('enderio:copper_alloy_nugget')
event.hide('enderio:energetic_alloy_nugget')
event.hide('enderio:vibrant_alloy_nugget')
event.hide('enderio:redstone_alloy_nugget')
event.hide('enderio:conductive_alloy_nugget')
event.hide('enderio:pulsating_alloy_nugget')
event.hide('enderio:dark_steel_nugget')
event.hide('enderio:soularium_nugget')
event.hide('enderio:end_steel_nugget')
 */
/* event.hide('enderio:copper_alloy_block')
event.hide('enderio:energetic_alloy_block')
event.hide('enderio:vibrant_alloy_block')
event.hide('enderio:redstone_alloy_block')
event.hide('enderio:conductive_alloy_block')
event.hide('enderio:pulsating_alloy_block')
event.hide('enderio:dark_steel_block')
event.hide('enderio:soularium_block')
event.hide('enderio:end_steel_block') */

/* event.hide('enderio:copper_alloy_grinding_ball')
event.hide('enderio:energetic_alloy_grinding_ball')
event.hide('enderio:vibrant_alloy_grinding_ball')
event.hide('enderio:redstone_alloy_grinding_ball')
event.hide('enderio:conductive_alloy_grinding_ball')
event.hide('enderio:pulsating_alloy_grinding_ball')
event.hide('enderio:dark_steel_grinding_ball')
event.hide('enderio:soularium_grinding_ball')
event.hide('enderio:end_steel_grinding_ball') */

event.hide('enderio:enderface_none')
event.hide('enderio:enderface_items')
event.hide('enderio:enderface_materials')
event.hide('enderio:enderface_machines')
event.hide('enderio:enderface_conduits')
event.hide('enderio:enderface_mobs')
event.hide('enderio:enderface_invpanel')

/* event.hide('enderio:void_chassis')
event.hide('enderio:ensouled_chassis') */

/* event.hide('enderio:pulsating_crystal')
event.hide('enderio:vibrant_crystal')
event.hide('enderio:ender_crystal')
event.hide('enderio:enticing_crystal')
event.hide('enderio:weather_crystal')
event.hide('enderio:prescient_crystal') */

event.hide('enderio:flour')
/* event.hide('enderio:powdered_coal')
event.hide('enderio:powdered_iron')
event.hide('enderio:powdered_gold')
event.hide('enderio:powdered_copper')
event.hide('enderio:powdered_tin')
event.hide('enderio:powdered_cobalt')
event.hide('enderio:powdered_ender_pearl')
event.hide('enderio:powdered_quartz')
event.hide('enderio:powdered_lapis_lazuli')
event.hide('enderio:powdered_obsidian')
event.hide('enderio:prescient_powder')
event.hide('enderio:vibrant_powder')
event.hide('enderio:pulsating_powder')
event.hide('enderio:ender_crystal_powder')
event.hide('enderio:photovoltaic_composite')
event.hide('enderio:soul_powder')
event.hide('enderio:confusing_powder')
event.hide('enderio:withering_powder') */

/* event.hide('enderio:silicon')
event.hide('enderio:infinity_rod')
event.hide('enderio:zombie_electrode')
event.hide('enderio:z_logic_controller')
event.hide('enderio:frank_n_zombie')
event.hide('enderio:ender_resonator')
event.hide('enderio:sentient_ender')
event.hide('enderio:skeletal_contractor')
event.hide('enderio:guardian_diode')
event.hide('enderio:double_layer_capacitor')
event.hide('enderio:octadic_capacitor')
event.hide('enderio:loot_capacitor')
event.hide('enderio:organic_green_dye')
event.hide('enderio:organic_brown_dye')
event.hide('enderio:organic_black_dye')
event.hide('enderio:photovoltaic_plate')
event.hide('enderio:nutritious_stick')
event.hide('enderio:plant_matter_green')
event.hide('enderio:plant_matter_brown')
event.hide('enderio:glider_wing')
event.hide('enderio:animal_token')
event.hide('enderio:monster_token')
event.hide('enderio:player_token')
event.hide('enderio:cake_base')
event.hide('enderio:black_paper')
event.hide('enderio:clayed_glowstone')
event.hide('enderio:nethercotta')
event.hide('enderio:enderios')
event.hide('enderio:location_printout')
event.hide('enderio:coordinate_selector')
event.hide('enderio:staff_of_levity')
event.hide('enderio:staff_of_travelling')
event.hide('enderio:travel_anchor')
event.hide('enderio:electromagnet')
event.hide('enderio:cold_fire_igniter')
event.hide('enderio:dark_steel_ladder')
event.hide('enderio:dark_steel_bars')
event.hide('enderio:dark_steel_door')
event.hide('enderio:dark_steel_trapdoor')
event.hide('enderio:end_steel_bars')
event.hide('enderio:reinforced_obsidian_block')
event.hide('enderio:soul_chain') */

event.hide('enderio:dark_steel_pressure_plate')
event.hide('enderio:soularium_pressure_plate')
event.hide('enderio:silent_dark_steel_pressure_plate')
event.hide('enderio:silent_soularium_pressure_plate')
event.hide('enderio:silent_oak_pressure_plate')
event.hide('enderio:silent_acacia_pressure_plate')
event.hide('enderio:silent_dark_oak_pressure_plate')
event.hide('enderio:silent_spruce_pressure_plate')
event.hide('enderio:silent_birch_pressure_plate')
event.hide('enderio:silent_jungle_pressure_plate')
event.hide('enderio:silent_crimson_pressure_plate')
event.hide('enderio:silent_warped_pressure_plate')
event.hide('enderio:silent_stone_pressure_plate')
event.hide('enderio:silent_polished_blackstone_pressure_plate')
event.hide('enderio:silent_heavy_weighted_pressure_plate')
event.hide('enderio:silent_light_weighted_pressure_plate')

event.hide('enderio:industrial_insulation_block')

/* event.hide('enderio:nutrient_distillation_bucket')
event.hide('enderio:dew_of_the_void_bucket')
event.hide('enderio:vapor_of_levity_bucket')
event.hide('enderio:hootch_bucket')
event.hide('enderio:rocket_fuel_bucket')
event.hide('enderio:liquid_sunshine_bucket')
event.hide('enderio:cloud_seed_bucket')
event.hide('enderio:cloud_seed_concentrated_bucket')
event.hide('enderio:fire_water_bucket') */

/* event.hide('enderio:primitive_alloy_smelter')
event.hide('enderio:alloy_smelter')
event.hide('enderio:wired_charger')
event.hide('enderio:creative_power') */
event.hide('enderio:stirling_generator')
/* event.hide('enderio:sag_mill')
event.hide('enderio:slice_and_splice')
event.hide('enderio:impulse_hopper')
event.hide('enderio:soul_binder')
event.hide('enderio:powered_spawner')
event.hide('enderio:energetic_photovoltaic_module')
event.hide('enderio:pulsating_photovoltaic_module')
event.hide('enderio:vibrant_photovoltaic_module')
event.hide('enderio:basic_capacitor_bank')
event.hide('enderio:advanced_capacitor_bank')
event.hide('enderio:vibrant_capacitor_bank')
event.hide('enderio:crafter')
event.hide('enderio:soul_engine')
event.hide('enderio:drain')
event.hide('enderio:dark_steel_sword')
 */
event.hide('expatternprovider:infinity_cell')


event.hide('ae2:ender_dust')

event.hide('apotheosis:inert_trident')


event.hide('advgenerators:turbine_blade')


event.hide('ae2:facade')


})//End Of File