
[items]

	[items.frames]
		#Enable the basic frame
		frameEnabled = true
		#Enable the waxed frame
		waxedFrameEnabled = true
		#Enable the honeyed frame
		honeyFrameEnabled = true
		#Enable the twisting frame
		twistingFrameEnabled = true
		#Enable the soothing frame
		soothingFrameEnabled = true
		#Enable the cold frame
		coldFrameEnabled = true
		#Enable the hot frame
		hotFrameEnabled = true
		#Enable the dry frame
		dryFrameEnabled = true
		#Enable the wet frame
		wetFrameEnabled = true
		#Enable the deadly frame
		deadlyFrameEnabled = true
		#Enable the restrictive frame
		restrictiveFrameEnabled = true

	[items.foods]
		#Enable honey bread
		honeyBreadEnabled = true
		#Enable honey porkchop
		honeyPorkchopEnabled = true
		#Enable ambrosia
		ambrosiaEnabled = true

	[items.misc]
		#Enable bee staff
		staffEnabled = true

