
#General Settings
[general]
	#Clay, Glowstone, Quartz, Redstone and Snow Generators will generate dust items, not blocks.
	generate_dust = false
	#Enable the Ore Generator.
	oreGeneratorEnable = true
	#Enable the Dye Generator.
	dyeGeneratorEnable = true

#OreGenerator Probabilities
[oregenerator]
	#Comma separated list of the items and probabilities (probability value between 0.00 and 1.00) to be used in the Ore Generator, format to use: "modid:itemname*probability" e.g. "minecraft:iron_ore*0.45"
	oreGeneratorItems = ["minecraft:coal_ore*0.50", "minecraft:iron_ore*0.45", "minecraft:gold_ore*0.25", "minecraft:lapis_ore*0.10", "minecraft:redstone_ore*0.10", "minecraft:diamond_ore*0.05", "minecraft:emerald_ore*0.02", "minecraft:nether_quartz_ore*0.00", "minecraft:ancient_debris*0.01", "minecraft:copper_ore*0.40", "minecraft:deepslate_coal_ore*0.49", "minecraft:deepslate_iron_ore*0.44", "minecraft:deepslate_copper_ore*0.39", "minecraft:deepslate_gold_ore*0.24", "minecraft:deepslate_lapis_ore*0.09", "minecraft:deepslate_redstone_ore*0.09", "minecraft:deepslate_diamond_ore*0.04", "minecraft:deepslate_emerald_ore*0.01"]

#Generator Settings
[gensettings]

	#Tier: 1
	[gensettings.1]
		#Ticks between every generation update.
		#Range: > 1
		interval = 100

	#Tier: 2
	[gensettings.2]
		#Ticks between every generation update.
		#Range: > 1
		interval = 80

	#Tier: 3
	[gensettings.3]
		#Ticks between every generation update.
		#Range: > 1
		interval = 60

	#Tier: 4
	[gensettings.4]
		#Ticks between every generation update.
		#Range: > 1
		interval = 40

	#Tier: 5
	[gensettings.5]
		#Ticks between every generation update.
		#Range: > 1
		interval = 20

